version: '3'
services:
  flyway:
    image: flyway/flyway
    command: "-url=jdbc:postgresql://db/postgres -schemas=postgres -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate"
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: .
      args:
        dbUser: "${POSTGRES_USER}"
        dbPassword: "${POSTGRES_PASSWORD}"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db